# Generated by Django 3.2 on 2021-05-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_chalkheluser_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_hex',
            field=models.CharField(default='FFFF', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
