# Generated by Django 3.2 on 2021-05-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
