# Generated by Django 3.2.4 on 2021-08-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='content_type',
            new_name='content_type1',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='object_id',
            new_name='object_id1',
        ),
    ]
