# Generated by Django 3.2.4 on 2021-06-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='member_count',
        ),
    ]
