# Generated by Django 3.2.4 on 2021-06-27 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0002_remove_post_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile/'),
        ),
        migrations.AlterUniqueTogether(
            name='forummember',
            unique_together={('forum', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('post', 'owner')},
        ),
    ]
