# Generated by Django 3.2 on 2021-05-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_forumfollower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='followers',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='forumfollower',
            old_name='user',
            new_name='member',
        ),
    ]
