# Generated by Django 3.2.4 on 2021-08-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20210809_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='content_type1',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='object_id1',
            new_name='object_id',
        ),
    ]
