# Generated by Django 3.2 on 2021-05-02 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0003_auto_20210502_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForumFollower',
            new_name='ForumMember',
        ),
    ]
