# Generated by Django 3.2.4 on 2021-08-09 18:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('forums', '0003_auto_20210809_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('object_id', 'owner', 'content_type')},
        ),
    ]
