# Generated by Django 3.2.4 on 2021-08-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_alter_post_media_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='post/image/'),
        ),
    ]
