# Generated by Django 3.2.4 on 2021-07-05 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0005_alter_comment_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('received_date', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(default=False)),
                ('message', models.TextField(max_length=5000)),
                ('receiving_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciving_user', to=settings.AUTH_USER_MODEL)),
                ('sending_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
