# Generated by Django 3.2.4 on 2021-08-09 09:12

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_auto_20210809_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_content_video',
            field=models.FileField(null=True, upload_to='post/video/', verbose_name=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
        ),
    ]
