# Generated by Django 3.2.4 on 2021-07-05 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sending_users',
            new_name='sending_user',
        ),
    ]
