# Generated by Django 3.2.4 on 2021-07-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_auto_20210705_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, default=11, on_delete=django.db.models.deletion.CASCADE, related_name='notification_for_post', to='forums.post'),
        ),
    ]
