# Generated by Django 3.2.4 on 2021-07-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_alter_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='', max_length=500),
        ),
    ]
