# Generated by Django 3.2.4 on 2021-08-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_auto_20210809_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_content',
            field=models.FileField(blank=True, null=True, upload_to='post/media_content/', verbose_name=''),
        ),
    ]
