# Generated by Django 3.2.4 on 2021-08-09 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0011_alter_post_media_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cause', models.CharField(default=None, max_length=255, unique=True)),
                ('affected_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_agent', to=settings.AUTH_USER_MODEL)),
                ('causing_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causing_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
