# Generated by Django 3.2.4 on 2021-08-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0013_auto_20210809_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='last_updated',
        ),
    ]
