# Generated by Django 3.2.4 on 2021-08-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0014_auto_20210809_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='cause',
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='affected_post', to='forums.post'),
            preserve_default=False,
        ),
    ]
