# Generated by Django 3.2.4 on 2021-08-09 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0015_auto_20210809_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='forums.comment'),
            preserve_default=False,
        ),
    ]
