# Generated by Django 3.2.4 on 2021-08-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0016_auto_20210809_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='causing_agent',
        ),
    ]
