# Generated by Django 3.2.4 on 2021-08-09 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0017_remove_notification_causing_agent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='CommentNotification',
        ),
    ]
