# Generated by Django 3.2.4 on 2021-08-09 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0018_rename_notification_commentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.PositiveSmallIntegerField(default=0)),
                ('affected_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_receiver', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='forums.vote')),
            ],
        ),
    ]
