# Generated by Django 3.2.4 on 2021-08-09 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('forums', '0020_auto_20210809_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.PositiveSmallIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('affected_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_agent', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='votenotification',
            name='affected_agent',
        ),
        migrations.RemoveField(
            model_name='votenotification',
            name='vote',
        ),
        migrations.DeleteModel(
            name='CommentNotification',
        ),
        migrations.DeleteModel(
            name='VoteNotification',
        ),
    ]
