# Generated by Django 3.2.4 on 2021-08-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0024_alter_notification_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tag',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
