# Generated by Django 3.2.4 on 2021-08-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0026_alter_notification_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='tag',
        ),
    ]
