# Generated by Django 3.2.4 on 2021-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0027_remove_notification_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
